#!/bin/bash

MYSELF_DIR=$(dirname $(readlink -f $0))

DOMAIN=$MYSELF_DIR/kvm*.xml

if [ -f $DOMAIN ]; then
   VM_NAME=$(basename $DOMAIN .xml)
else
   echo "error determining domain"
   exit 1
fi

GUEST_IPADDR=$(vmmctl get_ip $VM_NAME)

# ssh
iptables -t nat -D PREROUTING -p tcp --dport "31022" -j DNAT --to "$GUEST_IPADDR:22"
iptables -D FORWARD -d "$GUEST_IPADDR/32" -p tcp -m state --state NEW -m tcp --dport "22" -j ACCEPT
